openapi: '3.0.0'
info:
    title: 'Origin Organization I-REC API'
    description: 'Swagger documentation for the DSB'
    version: '0.1'
    contact: {}
tags: []
servers: []
components:
    securitySchemes:
        access-token:
            scheme: 'bearer'
            bearerFormat: 'JWT'
            type: 'http'
    schemas:
        PublishMessageDto:
            type: 'object'
            properties:
                fqcn:
                    type: 'string'
                    description: 'Fully qualified channel name (fcqn)'
                    example: 'test.channels.testapp.apps.testorganization.iam.ewc'
                payload:
                    type: 'string'
                    description: 'Any stringified payload like JSON, BASE64 etc'
                    example: '{"data": "test"}'
                signature:
                    type: 'string'
                    description: 'Compacted EcdsaSecp256k1Signature2019'
            required:
                - 'fqcn'
                - 'payload'
                - 'signature'
        MessageDTO:
            type: 'object'
            properties:
                payload:
                    type: 'string'
                    description: 'Any stringified payload like JSON, BASE64 etc'
                    example: '{"data": "test"}'
                sender:
                    type: 'string'
                    description: 'Sender of the message'
                    example: '{"data": "test"}'
                signature:
                    type: 'string'
                    description: 'Compacted EcdsaSecp256k1Signature2019'
            required:
                - 'payload'
                - 'sender'
                - 'signature'
        CreateChannelDto:
            type: 'object'
            properties:
                fqcn:
                    type: 'string'
                    description: 'Fully qualified channel name (fcqn)'
                    example: 'test.channels.testapp.apps.testorganization.iam.ewc'
            required:
                - 'fqcn'
paths:
    /message:
        post:
            operationId: 'MessageController_publish'
            parameters: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PublishMessageDto'
            responses:
                202:
                    description: 'Publish message'
                    content:
                        application/json:
                            schema:
                                type: 'string'
        get:
            operationId: 'MessageController_getNewFromChannel'
            parameters:
                - name: 'fqcn'
                  required: true
                  in: 'query'
                  description: 'Fully qualified channel name (fqcn)'
                  example: 'test.channels.testapp.apps.testorganization.iam.ewc'
                  schema:
                      type: 'string'
                - name: 'amount'
                  required: false
                  in: 'query'
                  description: 'Amount of messages to be returned in the request, default value is 100'
                  example: '1000'
                  schema:
                      type: 'string'
            responses:
                200:
                    description: 'Pull and returns messages from given channel'
                    content:
                        application/json:
                            schema:
                                type: 'array'
                                items:
                                    $ref: '#/components/schemas/MessageDTO'
    /channel:
        post:
            operationId: 'ChannelController_create'
            parameters: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateChannelDto'
            responses:
                202:
                    description: 'Creates a channel'
                    content:
                        application/json:
                            schema:
                                type: 'string'
